# Generated by Django 4.1 on 2022-09-06 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='shop',
            name='email',
            field=models.CharField(default='email', max_length=50),
        ),
        migrations.AlterField(
            model_name='shop',
            name='website',
            field=models.CharField(default='website', max_length=40),
        ),
    ]
